; Sloth Kubernetes - AWS + Hetzner Test Configuration
; Test cluster with 3 AWS nodes and 2 Hetzner nodes
; Includes Salt for configuration management and WireGuard for mesh networking
; SSH keys are auto-generated and saved to Pulumi state

(cluster
  (metadata
    (name "test-aws-hetzner")
    (environment "test")
    (description "Test cluster spanning AWS and Hetzner with Salt and WireGuard")
    (owner "test-team"))

  (cluster
    (type "rke2")
    (version "v1.29.0+rke2r1")
    (high-availability true)
    (multi-cloud true))

  ; Cloud providers
  (providers
    (aws
      (enabled true)
      (region "us-east-1"))
    (hetzner
      (enabled true)
      (token (env "HETZNER_TOKEN"))
      (location "nbg1")))

  ; WireGuard mesh networking
  (network
    (mode "wireguard")
    (pod-cidr "10.42.0.0/16")
    (service-cidr "10.43.0.0/16")
    (cross-provider-networking true)
    (wireguard
      (enabled true)
      (create true)
      (provider "hetzner")
      (region "nbg1")
      (subnet-cidr "10.8.0.0/24")
      (port 51820)
      (mesh-networking true)
      (auto-config true)))

  ; Salt configuration management
  (salt
    (enabled true)
    (master
      (provider "hetzner")
      (region "nbg1")
      (size "cx21")
      (name "salt-master"))
    (api
      (enabled true)
      (port 8000)
      (ssl true))
    (minion
      (auto-accept true)))

  (security
    ; SSH keys are auto-generated by Pulumi TLS provider
    ; Private key saved to: ~/.ssh/kubernetes-clusters/<stack-name>.pem
    ; Keys are exported to Pulumi state as: ssh_private_key, ssh_public_key
    (ssh
      (auto-generate true))
    (bastion
      (enabled true)
      (provider "hetzner")
      (region "nbg1")
      (size "cpx22")
      (name "bastion-test")))

  ; Node pools: 3 AWS + 2 Hetzner
  (node-pools
    ; AWS control plane (1 master)
    (aws-master
      (name "aws-master")
      (provider "aws")
      (region "us-east-1")
      (count 1)
      (roles master etcd)
      (size "t3.medium")
      (labels
        (cloud "aws")
        (role "control-plane")))

    ; AWS workers (2 nodes)
    (aws-workers
      (name "aws-workers")
      (provider "aws")
      (region "us-east-1")
      (count 2)
      (roles worker)
      (size "t3.medium")
      (labels
        (cloud "aws")
        (role "worker")))

    ; Hetzner workers (2 nodes)
    (hetzner-workers
      (name "hetzner-workers")
      (provider "hetzner")
      (region "nbg1")
      (count 2)
      (roles worker)
      (size "cpx22")
      (labels
        (cloud "hetzner")
        (role "worker"))))

  (kubernetes
    (version "v1.29.0")
    (distribution "rke2")
    (network-plugin "canal")
    (cluster-domain "cluster.local"))

  (monitoring
    (enabled false)))
