title: sloth-kubernetes
description: Multi-Cloud Kubernetes Orchestration in a Single Binary
baseurl: "/sloth-kubernetes"
url: "https://chalkan3.github.io"

theme: just-the-docs

# Logo
logo: "/assets/images/logo.png"

# Aux links for the upper right navigation
aux_links:
  "sloth-kubernetes on GitHub":
    - "//github.com/chalkan3/sloth-kubernetes"

# Color scheme
color_scheme: dark

# Footer content
footer_content: "Copyright &copy; 2025. Made with ❤️ by the sloth-kubernetes team."

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable copy code button
enable_copy_code_button: true

# Heading anchor links
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Collections for organizing different doc types
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: default
